### ISSUE TITLE
Ver 1.0.0のインストールスクリプトについて

### ISSUE THREAD

**Issue by gomi-kuzu** [RyodoTanaka/ompl_apps#7]
### くそいしゅ失礼します
Ver 1.0.0をインストールするのに
Ver 1.3.0のインストール説明にならって
`$ ./install/install-ompl-1.0.0-ubuntu.sh`
とすると

`./install/install-ompl-1.0.0-ubuntu.bash: 88 行: cd: ompl-1.0.0-Source: そのようなファイルやディレクトリはありません`
とエラー吐いて（その後cmake失敗で）止まりました 

`ompl-1.0.0-Source`ディレクトリがうまく指定できていないみたいなので
スマートな書き方はよくわかりませんが、とりあえず
`install-ompl-1.0.0-ubuntu.sh`の88行目を
`cd /home/inoma-ubu-s/ompl_apps/install/ompl-1.0.0-Source`
と強引なカンジに書きなおしてみたらうまくいきました

参考まで

**Comment by RyodoTanaka** [comment]
@gomi-kuzu 
ありがとうございます．
私の環境では起こったことのないエラーですね。。。
とりあえず解決策の提示までありがとうございますm(_ _)m

報告していただいたエラーは，Travisに検証を任せたいと思います．
